
version: 2

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      #- build-nightly
      - build-lts-21
      - build-lts-19
      - build-lts-18
      - build-lts-17


references:

  restore_backend_stack_cache: &restore_backend_stack_cache

  # Default branch / master

  default_cache_key: &default_cache_key
    v2-stack-{{ checksum "stack.yaml" }}-{{ checksum "wai-middleware-throttle.cabal" }}

  restore_stack_default_cache: &restore_stack_default_cache
    restore_cache:
      keys:
        - *default_cache_key
        - v2-stack-{{ checksum "stack.yaml" }}-
        - v2-stack

  save_stack_default_cache: &save_stack_default_cache
    save_cache:
      key: *default_cache_key
      paths:
        - ~/.stack
        - .stack-work

  # nightly

  nightly_cache_key: &nightly_cache_key
    v2-stack-nightly-{{ checksum "wai-middleware-throttle.cabal" }}

  restore_stack_nightly_cache: &restore_stack_nightly_cache
    restore_cache:
      keys:
        - *nightly_cache_key
        - v2-stack

  save_stack_nightly_cache: &save_stack_nightly_cache
    save_cache:
      key: *nightly_cache_key
      paths:
        - ~/.stack
        - .stack-work

  # lts-21

  lts-21_cache_key: &lts-21_cache_key
    v2-stack-lts-21-{{ checksum "wai-middleware-throttle.cabal" }}

  restore_stack_lts-21_cache: &restore_stack_lts-21_cache
    restore_cache:
      keys:
        - *lts-21_cache_key
        - v2-stack

  save_stack_lts-21_cache: &save_stack_lts-21_cache
    save_cache:
      key: *lts-21_cache_key
      paths:
        - ~/.stack
        - .stack-work

  # lts-19

  lts-19_cache_key: &lts-19_cache_key
    v2-stack-lts-19-{{ checksum "wai-middleware-throttle.cabal" }}

  restore_stack_lts-19_cache: &restore_stack_lts-19_cache
    restore_cache:
      keys:
        - *lts-19_cache_key
        - v2-stack

  save_stack_lts-19_cache: &save_stack_lts-19_cache
    save_cache:
      key: *lts-19_cache_key
      paths:
        - ~/.stack
        - .stack-work

  # lts-18

  lts-18_cache_key: &lts-18_cache_key
    v2-stack-lts-18-{{ checksum "wai-middleware-throttle.cabal" }}

  restore_stack_lts-18_cache: &restore_stack_lts-18_cache
    restore_cache:
      keys:
        - *lts-18_cache_key
        - v2-stack

  save_stack_lts-18_cache: &save_stack_lts-18_cache
    save_cache:
      key: *lts-18_cache_key
      paths:
        - ~/.stack
        - .stack-work

  # lts-17

  lts-17_cache_key: &lts-17_cache_key
    v2-stack-lts-17-{{ checksum "wai-middleware-throttle.cabal" }}

  restore_stack_lts-17_cache: &restore_stack_lts-17_cache
    restore_cache:
      keys:
        - *lts-17_cache_key
        - v2-stack

  save_stack_lts-17_cache: &save_stack_lts-17_cache
    save_cache:
      key: *lts-17_cache_key
      paths:
        - ~/.stack
        - .stack-work

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-22.37
    environment:
      STACK_ARGS: "--jobs 2"
    steps:
      - checkout
      - *restore_stack_default_cache
      - run: stack setup $STACK_ARGS
      - run: stack install $STACK_ARGS --only-dependencies --test --no-run-tests
      - *save_stack_default_cache
      - run: stack test $STACK_ARGS wai-middleware-throttle

  build-nightly:
    docker:
      - image: fpco/stack-build:latest
    environment:
      STACK_ARGS: "--resolver nightly-$(date +%F) --no-terminal --jobs 2"
    steps:
      - checkout
      - *restore_stack_nightly_cache
      - run: stack setup $STACK_ARGS
      - run: stack install $STACK_ARGS --only-dependencies --test --no-run-tests
      - *save_stack_nightly_cache
      - run: stack test $STACK_ARGS wai-middleware-throttle

  build-lts-21:
    docker:
      - image: fpco/stack-build:lts-21
    environment:
      STACK_ARGS: "--resolver lts-21 --no-terminal --jobs 2"
    steps:
      - checkout
      - *restore_stack_lts-21_cache
      - run: stack setup $STACK_ARGS
      - run: stack install $STACK_ARGS --only-dependencies --test --no-run-tests
      - *save_stack_lts-21_cache
      - run: stack test $STACK_ARGS wai-middleware-throttle

  build-lts-19:
    docker:
      - image: fpco/stack-build:lts-19
    environment:
      STACK_ARGS: "--resolver lts-19 --no-terminal --jobs 2"
    steps:
      - checkout
      - *restore_stack_lts-19_cache
      - run: stack setup $STACK_ARGS
      - run: stack install $STACK_ARGS --only-dependencies --test --no-run-tests
      - *save_stack_lts-19_cache
      - run: stack test $STACK_ARGS wai-middleware-throttle

  build-lts-18:
    docker:
      - image: fpco/stack-build:lts-18
    environment:
      STACK_ARGS: "--resolver lts-18 --no-terminal --jobs 2"
    steps:
      - checkout
      - *restore_stack_lts-18_cache
      - run: stack setup $STACK_ARGS
      - run: stack install $STACK_ARGS --only-dependencies --test --no-run-tests
      - *save_stack_lts-18_cache
      - run: stack test $STACK_ARGS wai-middleware-throttle

  build-lts-17:
    docker:
      - image: fpco/stack-build:lts-17
    environment:
      STACK_ARGS: "--resolver lts-17 --no-terminal --jobs 2"
    steps:
      - checkout
      - *restore_stack_lts-17_cache
      - run: stack install $STACK_ARGS --only-dependencies --test --no-run-tests
      - *save_stack_lts-17_cache
      - run: stack test $STACK_ARGS wai-middleware-throttle
